<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7-boltserver:
    roles:
      - default
      - boltserver
      - target
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
  el7-target:
    roles:
      - target
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
  el8-boltserver:
    roles:
      - boltserver
      - target
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
  el8-target:
    roles:
      - target
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
#  el6-boltserver:
#    roles:
#      - boltserver
#      - target
#    platform:   el-6-x86_64
#    box:        centos/6
#    hypervisor: <%= hypervisor %>
#    yum_repos:
#      epel:
#        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
#        gpgkeys:
#          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
#  el6-target:
#    roles:
#      - target
#    platform:   el-6-x86_64
#    box:        centos/6
#    hypervisor: <%= hypervisor %>
#    yum_repos:
#      epel:
#        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
#        gpgkeys:
#          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
#
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
